replicaCount: 1

image:
  repository: myregistry/hello-k8s
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 3000

# A custom value for our greeting
greeting: "Hello Kubernetes!"
