apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "hello-k8s.fullname" .}}
  labels:
    app: {{include "hello-k8s.name" .}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{include "hello-k8s.name" .}}
  template:
    metadata:
      labels:
        app: {{include "hello-k8s.name" .}}
    spec:
      containers:
        - name: {{include "hello-k8s.name" .}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{.Values.service.port}}
          env:
            - name: GREETING
              value: {{.Values.greeting | quote}}
